[project]
name = "nanogpt"
version = "0.1.0"
description = "torch implementation of gpt"
readme = "README.md"
authors = [
    { name = "urlicht", email = "urlicht@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.5.0",
    "tqdm>=4.66.0",
    "tiktoken>=0.12.0",
    "torch>=2.10.0",
    "numpy>=2.4.2",
    "tensorboard>=2.20.0",
]

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
